# Generated by Django 4.2.1 on 2023-06-19 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fieldKey", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TrackKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trackKey", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default/profile_pic_default.png",
                        null=True,
                        upload_to="post/",
                    ),
                ),
                ("team_name", models.CharField(max_length=30)),
                ("title", models.TextField()),
                ("recruit_date", models.TextField()),
                ("link", models.TextField()),
                ("member", models.TextField()),
                ("about_us", models.TextField()),
                ("pub_date", models.DateTimeField()),
                (
                    "fieldKey",
                    models.ManyToManyField(related_name="post", to="post.fieldkey"),
                ),
                (
                    "trackKey",
                    models.ManyToManyField(related_name="post", to="post.trackkey"),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
