# Generated by Django 4.2.2 on 2023-06-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('under_review', '검토중'), ('accept', '수락됨'), ('reject', '거절됨')], default='under_review', max_length=15)),
                ('short_text', models.TextField(max_length=500)),
                ('reply', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldKey', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TrackKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackKey', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default/profile_pic_default.png', null=True, upload_to='post/')),
                ('team_name', models.CharField(max_length=30)),
                ('title', models.TextField()),
                ('recruit_date', models.TextField()),
                ('link', models.TextField(blank=True)),
                ('member', models.TextField()),
                ('about_us', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('isSave', models.BooleanField(default=False)),
                ('fieldKey', models.ManyToManyField(related_name='post', to='post.fieldkey')),
                ('trackKey', models.ManyToManyField(related_name='post', to='post.trackkey')),
            ],
        ),
    ]
