# Generated by Django 4.2.2 on 2023-06-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fieldKey',
            field=models.ManyToManyField(related_name='post', to='post.fieldkey'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default/profile_pic_default.png', null=True, upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='trackKey',
            field=models.ManyToManyField(related_name='post', to='post.trackkey'),
        ),
    ]
