# Generated by Django 4.2.2 on 2023-06-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='respond_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
