# Generated by Django 4.2.2 on 2023-06-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_apply_respond_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='short_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
