# Generated by Django 4.2.1 on 2023-06-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("post", "0004_rename_category_fieldkey_rename_keyword_trackkey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.profile"
            ),
        ),
    ]
