# Generated by Django 4.2.2 on 2023-06-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_apply_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='status',
        ),
        migrations.AddField(
            model_name='apply',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
