# Generated by Django 4.2.1 on 2023-06-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_remove_apply_is_accept_apply_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="isSave",
            field=models.BooleanField(default=False),
        ),
    ]
