# Generated by Django 4.2.2 on 2023-06-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_apply_is_accept_apply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='reply',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
