# Generated by Django 4.2.1 on 2023-06-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_post_issave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="link",
            field=models.TextField(blank=True),
        ),
    ]
