# Generated by Django 4.2.2 on 2023-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.TextField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성'), ('etc', '기타')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
