# Generated by Django 4.2.2 on 2023-06-17 16:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_about_me_profile_age_profile_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='Project/media/profile_pic_default.png', upload_to=accounts.models.profile_pic_path),
        ),
    ]
