# Generated by Django 4.2.2 on 2023-06-17 16:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/profile_pic_default.png', upload_to=accounts.models.profile_pic_path),
        ),
    ]
