# Generated by Django 4.2.1 on 2023-06-19 18:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="default/profile_pic_default.png",
                upload_to=accounts.models.profile_pic_path,
            ),
        ),
    ]
